name: vendeta
description: VendETA Flutter Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  powers: ^0.1.0
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  freezed_annotation: ^0.12.0
  redux_epics: ^0.14.0
  rxdart: any
  icon_shadow: ^1.0.1
  url_launcher: ^5.0.3
  animated_text_kit: ^1.3.0
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  dwds: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  freezed: any
  analyzer: any

flutter:

  uses-material-design: true

  assets:
  - icons/

